/** Static class name map — avoids CSS module bundling issues with tsup */
export const styles = {
  spinnerSpin: 'goey-spinnerSpin',
  wrapper: 'goey-wrapper',
  blobSvg: 'goey-blobSvg',
  content: 'goey-content',
  contentCompact: 'goey-contentCompact',
  contentExpanded: 'goey-contentExpanded',
  header: 'goey-header',
  iconWrapper: 'goey-iconWrapper',
  title: 'goey-title',
  titleDefault: 'goey-titleDefault',
  titleSuccess: 'goey-titleSuccess',
  titleError: 'goey-titleError',
  titleWarning: 'goey-titleWarning',
  titleInfo: 'goey-titleInfo',
  titleLoading: 'goey-titleLoading',
  description: 'goey-description',
  actionWrapper: 'goey-actionWrapper',
  actionButton: 'goey-actionButton',
  actionDefault: 'goey-actionDefault',
  actionSuccess: 'goey-actionSuccess',
  actionError: 'goey-actionError',
  actionWarning: 'goey-actionWarning',
  actionInfo: 'goey-actionInfo',
} as const
